version: "3"
services:
  archive:
    container_name: ms-archive-test
    image: 'ms-archive:latest'
    network_mode: bridge
    restart: always
    ports:
      - "9050:8080"
    environment:
      - JAVA_OPTS=-server -Dfile.encoding=UTF-8 -Xms128m -Xmx256m
      - SPRING_PROFILES_ACTIVE=test
	  - SPRING_CLOUD_CONFIG_URI=<config server URL>
      - SPRING_CLOUD_CONFIG_USERNAME=<config server username>
      - SPRING_CLOUD_CONFIG_PASSWORD=<config server password>

